### ISSUE TITLE
prop:Help Example how make callout?

### ISSUE THREAD

**Issue by remotejob** [CyCoreSystems/agi#11]
How make simple callout:
Callout(+3584512028100) ---> playfile ---> (test.wav) ---> hangup()
So simple advertisement. (Don't make call in)

Something like 
./callout

extension something like:
 
exten => ${CALLOUT},1,Answer  ; ?? maybe not needed ?
same => n,Dial(PJSIP/+358541202800@cuuma,30,S(14400))
same => n,Playback(test)
same => n,Hangup()

Thanks.

**Comment by Ulexus** [comment]
AGI does not offer any facility to generate a call from nothing.  This must be done through some other facility.  The most common mechanisms for this are probably:

- [Call files](https://wiki.asterisk.org/wiki/display/AST/Asterisk+Call+Files)
- AMI [Originate](https://wiki.asterisk.org/wiki/display/AST/Asterisk+17+ManagerAction_Originate)
- ARI [Originate](https://wiki.asterisk.org/wiki/display/AST/Asterisk+17+Channels+REST+API#Asterisk17ChannelsRESTAPI-originate)

**Comment by remotejob** [comment]
Ok!  thanks
