### ISSUE TITLE
agi.NewEAGI blocks

### ISSUE THREAD

**Issue by angadn** [CyCoreSystems/agi#2]
I'm afraid I may have introduced a bug with that last PR - In my setup, `agi.NewEAGI` and `agi.NewStdio` both seem to block indefinitely.

My `extensions.conf`:
```
exten => _+1NXXXXXXXXX,1,Answer
exten => _+1NXXXXXXXXX,n,EAGI(/usr/src/eagi-go)
exten => _+1NXXXXXXXXX,n,Wait(30) ; Without this, the call seems to end in a snap? Is EAGI non-blocking?
```

My Go code:
```
ioutil.WriteFile("/tmp/Invoked EAGI", []byte{}, 0644) // Can't think of a more elegant way to debug ATM
agi := agi.NewEAGI()
ioutil.WriteFile("/tmp/EAGI Script Entered", []byte{}, 0644) 
if err := agi.Answer(); err == nil {
    ...
```

An `ls /tmp` shows:
```
Invoked EAGI
```

FWIW, running inside Docker - will update if I am able to solve this.

**Comment by Ulexus** [comment]
Your program is almost certainly dying.  If you look at the Asterisk console, it should be printing the stderr output from the AGI execution.  There should be a stack trace there.

**Comment by Ulexus** [comment]
I suspect the problem is with your implemenation to open file descriptor 3.  I would expect that you would use something like this to open FD 3:

```go
eagi, err := os.Open("/dev/fd/3")
```

**Comment by angadn** [comment]
Just spent a bunch of time playing around with `agi set debug on` and `-cvvvvv`, but  I see no stack-trace either in the console, or the Asterisk process' Stdout/err streams. Also, as mentioned, the `NewStdio` seems to block too - and that isn't going anywhere near `fd/3`! Are you saying its a crash because I'm having to rely on the final `Wait` to keep the call alive?

**Comment by angadn** [comment]
`/proc/<PID>/fd/3` seems to be more likely?

**Comment by Ulexus** [comment]
Ah, sorry.  I missed you saying that NewStdio was failing, too.  I'll have to sanity check the basic operation here.  I'm not sure that I'm actually using this library anywhere.  I think I just whipped it up for testing some time ago.

**Comment by angadn** [comment]
@Ulexus I've attempted to write a simple Golang script without this library, to simply read the EAGI stream, but running into the same issue. Opening a question on SO: http://stackoverflow.com/questions/43353694/accessing-fd-3-for-asterisk-eagi

**Comment by angadn** [comment]
This might just be an issue with Docker: https://github.com/docker/docker/issues/6607

**Comment by angadn** [comment]
I'm going to try this: https://golang.org/pkg/syscall/#Read to see if it lets me read FD 3

**Comment by Ulexus** [comment]
Closing old issue.  Please re-open if this is still a problem.
